apiVersion: v1
kind: Pod
metadata:
  labels:
    name: gasdb-pod
  name: gasdb-pod
spec:
  containers:
  - env:
    - name: MYSQL_USER
      value: "gaslog"
    - name: MYSQL_PASSWORD
      value: "data4Life!"
    - name: MYSQL_DATABASE
      value: "gaslog"
    image: openshift3/mysql-55-rhel7
    imagePullPolicy: IfNotPresent
    name: gasdb-pod
    volumeMounts:
    - mountPath: "/var/lib/mysql/data"
      name: dbvol
    ports:
    - containerPort: 3306
      protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
  volumes:
  - name: dbvol
    persistentVolumeClaim:
      claimName: gasdb-pvc
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
