apiVersion: extensions/v1beta1
kind: HorizontalPodAutoscaler
metadata:
  name: gasapp-hpa
spec:
  scaleRef:
    kind: ReplicationController 
    name: gasapp-rc
    apiVersion: v1 
    subresource: scale
  minReplicas: 1 
  maxReplicas: 5
  cpuUtilization:
    targetPercentage: 20
